name: golangci-lint
on:
  push:
    branches:
      - '*'
    paths-ignore: # 下列文件的变更不触发工作流
      - README.md
      - LICENSE

permissions:
  contents: read

jobs:
  golangCi:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false

      - name: 显示当前目录
        run: |
          pwd            # 打印当前工作目录
          ls             # 列出当前目录内容

      - name: golangCi-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          args: --skip-dirs=structuitl/data_struct/TestStruct
          # 这里无需指定 working-directory，默认就是当前目录
          # 其他可选参数可以根据需要取消注释并配置
          # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0
          # only-new-issues: true
          # skip-cache: true
          # skip-pkg-cache: true
          # skip-build-cache: true
          # install-mode: "goinstall"